### ISSUE TITLE
PUT only permissions

### ISSUE THREAD

**Issue by mohankv** [SoftInstigate/restheart#99] opened 2016-01-28 19:22 UTC
I would like to use API for user registration also. I have configured db based Identity manager with DbIdentityManager. And Permissions like below.

permissions:
#Users with role 'admin' can do anything
    - role: admin
      predicate: path-prefix[path="/"]

#Unauthenticated user can only GET any resource under the /io/tracks/ URI
    - role: $unauthenticated
      predicate: path-prefix[path="/io/tracks/"] and method[value="GET"]

#Unauthenticated user can do PUT (send _id and password that creates new account in db
    - role: $unauthenticated
      predicate: path-prefix[path="/io/accounts"] and method[value="PUT"]

Above paths are accessible with admin logged in, but not for unauthenticated users. How to configure permissions for unauthenticated users to send PUT request for registration functionality. Any good and thorough documentation on this available on this?

Thanks,

**Comment by mohankv** [comment] 2016-01-29 05:02
Is there any other ways we can insert registration details of an user? (POST or PUT). Please note that user is unauthenticated in registration pages.

**Comment by mkjsix** [comment] 2016-01-29 09:11
At first sight your configuration looks correct to me, so I'm moving this question to @ujibang 

To answer your second question: there are many possibile ways for managing users, for example with the `DbIdentityManager` you can POST new users. See https://softinstigate.atlassian.net/wiki/x/C4AWAQ for an example of provisioning a number of users directly into MongoDB.

**Comment by mkjsix** [comment] 2016-02-04 08:27
Closing this as a duplicate of #100 (follow up there)

**Closed by mkjsix** 2016-02-04 08:27 UTC
Labels: duplicate, question
