### ISSUE TITLE
Unable to start RESTHeart 8.1.4 on Windows 10 due to faulty handling of plugins directory

### ISSUE THREAD

**Issue by dev-indb** [SoftInstigate/restheart#531] opened 2024-11-15 19:53 UTC
**Describe the bug**

I'm experiencing difficulties starting RESTHeart 8.1.4 on Windows 10, seemingly due to faulty handling of the plugins folder. I've attempted nearly every syntax variation for specifying the plugins-directory, but each time I encounter the same issues:

- Plugins Folder Ignored: RESTHeart starts successfully but only responds to ping requests and fails to connect to my MongoDB instance.
- Path Issues: RESTHeart crashes at startup with a path-related error.

**To Reproduce**

1. Configuration File (restheart.yml):

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;I have configured the core module in my `restheart.yml` as follows:
```
# base configuration for core module
core:
  # The name of this instance. Displayed in log, also allows to implement instance specific custom code
  name: default

  # The directory containing the plugins jars.
  # The path is either absolute (starts with /) or relative to the restheart.jar file
  # Just add the plugins jar to plugins-directory and they will be automatically
  # added to the classpath and registered.
  plugins-directory: plugins
  # Below are configurations for Windows
  # plugins-directory: C:\\git\\restheart\\plugins
  # plugins-directory: /\\?\C:\git\restheart\plugins
  # plugins-directory: /C:\\git\\restheart\\plugins
  # plugins-directory: /C:\git\restheart\plugins
  # plugins-directory: /C:/git/restheart/plugins
  # plugins-directory: .plugins
  # plugins-directory: /plugins
  # plugins-directory: \
  # plugins-directory: /c/git/restheart/plugins
```
2. Starting RESTHeart:

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;I attempt to start RESTHeart using the following command in the Windows Command Prompt:

`   C:\git\restheart>"C:\Users\xyz\.jdks\temurin-21.0.3\bin\java" -jar restheart.jar restheart.yml -s`

3. See error

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;RESTHeart crashes at startup with the following error

`   java.nio.file.InvalidPathException: Illegal char <:> at index 2: /C:/git/restheart/plugins/restheart-graphql.jar`

**Additional context**

1. Logs

```
C:\git\restheart>"C:\Users\xyz\.jdks\temurin-21.0.3\bin\java" -jar restheart.jar restheart.yml -s
22:10:55.374 [main] INFO org.restheart.Bootstrapper - Starting RESTHeart instance default
22:10:55.376 [main] INFO org.restheart.Bootstrapper - Version 8.1.4
22:10:55.396 [main] DEBUGorg.restheart.Bootstrapper - Configuration:
....
 22:10:55.399 [main] INFO  org.restheart.Bootstrapper - Logging to file restheart.log with level TRACE
 22:10:55.399 [main] INFO  org.restheart.Bootstrapper - Logging to console with level TRACE
 22:10:55.410 [main] INFO  o.r.configuration.Configuration - Overriding configuration from environment variable RHO
 22:10:55.410 [main] INFO  o.r.configuration.Configuration -        /fileRealmAuthenticator/users[userid='admin']/password -> **********
 22:10:55.411 [main] TRACE o.r.configuration.Configuration - configuration paramenter "name" set to "default"
 22:10:55.411 [main] TRACE o.r.configuration.Configuration - configuration paramenter "plugins-directory" set to "plugins"
 22:10:55.412 [main] TRACE o.r.configuration.Configuration - configuration paramenter "io-threads" set to "0"
 22:10:55.412 [main] TRACE o.r.configuration.Configuration - configuration paramenter "workers-scheduler-parallelism" set to "0"
 22:10:55.412 [main] TRACE o.r.configuration.Configuration - configuration paramenter "workers-scheduler-max-pool-size" set to "256"
 22:10:55.413 [main] TRACE o.r.configuration.Configuration - configuration paramenter "buffers-pooling" set to "true"
 22:10:55.413 [main] TRACE o.r.configuration.Configuration - configuration paramenter "buffer-size" set to "16364"
 22:10:55.414 [main] TRACE o.r.configuration.Configuration - configuration paramenter "direct-buffers" set to "true"
 22:10:55.414 [main] TRACE o.r.configuration.Configuration - configuration paramenter "/http-listener/enabled" set to "true"
 22:10:55.415 [main] TRACE o.r.configuration.Configuration - configuration paramenter "/http-listener/host" set to "localhost"
 22:10:55.418 [main] TRACE o.r.configuration.Configuration - configuration paramenter "/http-listener/port" set to "8080"
 22:10:55.419 [main] TRACE o.r.configuration.Configuration - configuration paramenter "/https-listener/enabled" set to "false"
 22:10:55.419 [main] TRACE o.r.configuration.Configuration - configuration paramenter "/https-listener/host" set to "localhost"
 22:10:55.419 [main] TRACE o.r.configuration.Configuration - configuration paramenter "/https-listener/port" set to "4443"
 22:10:55.420 [main] TRACE o.r.configuration.Configuration - configuration paramenter "/ajp-listener/enabled" set to "false"
 22:10:55.420 [main] TRACE o.r.configuration.Configuration - configuration paramenter "/ajp-listener/host" set to "localhost"
 22:10:55.420 [main] TRACE o.r.configuration.Configuration - configuration paramenter "/ajp-listener/port" set to "8009"
 22:10:55.421 [main] TRACE o.r.configuration.Configuration - configuration parameter proxies not specified in the configuration file, using its default value null
 22:10:55.421 [main] TRACE o.r.configuration.Configuration - configuration parameter static-resources not specified in the configuration file, using its default value null
 22:10:55.421 [main] TRACE o.r.configuration.Configuration - configuration paramenter "log-to-file" set to "true"
 22:10:55.422 [main] TRACE o.r.configuration.Configuration - configuration paramenter "log-file-path" set to "restheart.log"
 22:10:55.422 [main] TRACE o.r.configuration.Configuration - configuration paramenter "log-to-console" set to "true"
 22:10:55.423 [main] TRACE o.r.configuration.Configuration - configuration paramenter "ansi-console" set to "true"
 22:10:55.423 [main] TRACE o.r.configuration.Configuration - configuration paramenter "requests-log-mode" set to "1"
 22:10:55.436 [main] INFO  o.restheart.plugins.PluginsScanner - Found plugin jar /C:/git/restheart/plugins/restheart-graphql.jar
 22:10:55.437 [main] INFO  o.restheart.plugins.PluginsScanner - Found plugin jar /C:/git/restheart/plugins/restheart-metrics.jar
 22:10:55.438 [main] INFO  o.restheart.plugins.PluginsScanner - Found plugin jar /C:/git/restheart/plugins/restheart-mongoclient-provider.jar
 22:10:55.438 [main] INFO  o.restheart.plugins.PluginsScanner - Found plugin jar /C:/git/restheart/plugins/restheart-mongodb.jar
 22:10:55.439 [main] INFO  o.restheart.plugins.PluginsScanner - Found plugin jar /C:/git/restheart/plugins/restheart-polyglot.jar
 22:10:55.440 [main] INFO  o.restheart.plugins.PluginsScanner - Found plugin jar /C:/git/restheart/plugins/restheart-security.jar
 22:10:55.442 [main] DEBUG o.restheart.plugins.PluginsScanner - Found lib jar /C:/git/restheart/plugins/lib/commons-codec-1.17.1.jar
 22:10:55.443 [main] DEBUG o.restheart.plugins.PluginsScanner - Found lib jar /C:/git/restheart/plugins/lib/commons-collections-3.2.2.jar
 22:10:55.443 [main] DEBUG o.restheart.plugins.PluginsScanner - Found lib jar /C:/git/restheart/plugins/lib/commons-digester-2.1.jar
 22:10:55.444 [main] DEBUG o.restheart.plugins.PluginsScanner - Found lib jar /C:/git/restheart/plugins/lib/commons-io-2.15.1.jar
 22:10:55.445 [main] DEBUG o.restheart.plugins.PluginsScanner - Found lib jar /C:/git/restheart/plugins/lib/commons-logging-1.2.jar
 22:10:55.447 [main] DEBUG o.restheart.plugins.PluginsScanner - Found lib jar /C:/git/restheart/plugins/lib/commons-validator-1.7.jar
 22:10:55.448 [main] DEBUG o.restheart.plugins.PluginsScanner - Found lib jar /C:/git/restheart/plugins/lib/graphql-java-21.5.jar
 22:10:55.448 [main] DEBUG o.restheart.plugins.PluginsScanner - Found lib jar /C:/git/restheart/plugins/lib/handy-uri-templates-2.1.8.jar
 22:10:55.449 [main] DEBUG o.restheart.plugins.PluginsScanner - Found lib jar /C:/git/restheart/plugins/lib/icu4j-24.1.0.jar
 22:10:55.450 [main] DEBUG o.restheart.plugins.PluginsScanner - Found lib jar /C:/git/restheart/plugins/lib/jackson-annotations-2.14.2.jar
 22:10:55.450 [main] DEBUG o.restheart.plugins.PluginsScanner - Found lib jar /C:/git/restheart/plugins/lib/jackson-core-2.14.2.jar
 22:10:55.454 [main] DEBUG o.restheart.plugins.PluginsScanner - Found lib jar /C:/git/restheart/plugins/lib/jackson-databind-2.14.2.jar
 22:10:55.455 [main] DEBUG o.restheart.plugins.PluginsScanner - Found lib jar /C:/git/restheart/plugins/lib/java-dataloader-3.2.1.jar
 22:10:55.455 [main] DEBUG o.restheart.plugins.PluginsScanner - Found lib jar /C:/git/restheart/plugins/lib/java-jwt-4.4.0.jar
 22:10:55.456 [main] DEBUG o.restheart.plugins.PluginsScanner - Found lib jar /C:/git/restheart/plugins/lib/jBCrypt-0.4.3.jar
 22:10:55.457 [main] DEBUG o.restheart.plugins.PluginsScanner - Found lib jar /C:/git/restheart/plugins/lib/joda-time-2.10.2.jar
 22:10:55.457 [main] DEBUG o.restheart.plugins.PluginsScanner - Found lib jar /C:/git/restheart/plugins/lib/js-language-24.1.0.jar
 22:10:55.458 [main] DEBUG o.restheart.plugins.PluginsScanner - Found lib jar /C:/git/restheart/plugins/lib/json-20240303.jar
 22:10:55.459 [main] DEBUG o.restheart.plugins.PluginsScanner - Found lib jar /C:/git/restheart/plugins/lib/metrics-jvm-4.2.28.jar
 22:10:55.459 [main] DEBUG o.restheart.plugins.PluginsScanner - Found lib jar /C:/git/restheart/plugins/lib/org.everit.json.schema-1.14.4.jar
 22:10:55.460 [main] DEBUG o.restheart.plugins.PluginsScanner - Found lib jar /C:/git/restheart/plugins/lib/polyglot-24.1.0.jar
 22:10:55.461 [main] DEBUG o.restheart.plugins.PluginsScanner - Found lib jar /C:/git/restheart/plugins/lib/re2j-1.6.jar
 22:10:55.464 [main] DEBUG o.restheart.plugins.PluginsScanner - Found lib jar /C:/git/restheart/plugins/lib/reactive-streams-1.0.3.jar
 22:10:55.465 [main] DEBUG o.restheart.plugins.PluginsScanner - Found lib jar /C:/git/restheart/plugins/lib/regex-24.1.0.jar
 22:10:55.465 [main] DEBUG o.restheart.plugins.PluginsScanner - Found lib jar /C:/git/restheart/plugins/lib/simpleclient-0.16.0.jar
 22:10:55.466 [main] DEBUG o.restheart.plugins.PluginsScanner - Found lib jar /C:/git/restheart/plugins/lib/simpleclient_common-0.16.0.jar
 22:10:55.467 [main] DEBUG o.restheart.plugins.PluginsScanner - Found lib jar /C:/git/restheart/plugins/lib/simpleclient_dropwizard-0.16.0.jar
 22:10:55.468 [main] DEBUG o.restheart.plugins.PluginsScanner - Found lib jar /C:/git/restheart/plugins/lib/simpleclient_tracer_common-0.16.0.jar
 22:10:55.469 [main] DEBUG o.restheart.plugins.PluginsScanner - Found lib jar /C:/git/restheart/plugins/lib/simpleclient_tracer_otel-0.16.0.jar
 22:10:55.469 [main] DEBUG o.restheart.plugins.PluginsScanner - Found lib jar /C:/git/restheart/plugins/lib/simpleclient_tracer_otel_agent-0.16.0.jar
 22:10:55.470 [main] DEBUG o.restheart.plugins.PluginsScanner - Found lib jar /C:/git/restheart/plugins/lib/tika-core-2.9.2.jar
 22:10:55.470 [main] DEBUG o.restheart.plugins.PluginsScanner - Found lib jar /C:/git/restheart/plugins/lib/truffle-api-24.1.0.jar
 22:10:55.471 [main] DEBUG o.restheart.plugins.PluginsScanner - Found lib jar /C:/git/restheart/plugins/lib/zxcvbn-1.9.0.jar
 22:10:55.479 [main] ERROR org.restheart.Bootstrapper - Linkage error instantiating plugins. Check that all plugins were compiled against restheart-commons v8.1.4
 java.lang.ExceptionInInitializerError: null
        at org.restheart.plugins.PluginsFactory.providers(PluginsFactory.java:180)
Caused by: java.nio.file.InvalidPathException: Illegal char <:> at index 2: /C:/git/restheart/plugins/restheart-graphql.jar
        at java.base/sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:204)
22:10:55.481 [main] INFO org.restheart.Bootstrapper - Stopping RESTHeart...
 22:10:55.481 [main] INFO org.restheart.Bootstrapper - Cleaning up temporary directories...
 22:10:55.482 [main] INFO org.restheart.Bootstrapper - RESTHeart stopped
```

2. Debugger view

![image](https://github.com/user-attachments/assets/bfb836de-a79f-4b6e-af29-2ef141d094b1)

It seems that it's a JDK bug... but it won't be fixed.
[WindowsPathParser throws InvalidPathException: Illegal char <:> at index 2](https://bugs.openjdk.org/browse/JDK-8314511)

**Comment by ujibang** [comment] 2024-11-18 10:00
Hello @dev-indb 

I just pushed a possibile fix for this, however I don't have Windows machine to try it. Can you please test it?

To try it you need to build it from source. For this, you'll need `git` and `java 21`.

```
> git clone --depth 1 git@github.com:SoftInstigate/restheart.git
> cd restheart
> git checkout 8.1.x
> .\mvnw clean package
> set RHO="/core/plugins-directory->'C:\git\restheart\plugins'"
> java -jar core\target\restheart.jar
```

**Comment by mkjsix** [comment] 2024-11-18 18:56
I'm testing 8.1.x on Windows 10 and it can't event build, it fails running the PluginTest class with:

`[ERROR] org.restheart.plugins.PluginsTest -- Time elapsed: 1.350 s <<< ERROR!
org.mockito.exceptions.base.MockitoException: Cannot instrument class org.restheart.plugins.PluginsScanner because it or one of its supertypes could not be initialized
        at org.restheart.plugins.PluginsTest.mockPluginsScanner(PluginsTest.java:129)
        at org.restheart.plugins.PluginsTest.before(PluginsTest.java:56)
Caused by: java.nio.file.InvalidPathException: Illegal char <:> at index 2: /C:/Users/mauri/restheart/core/target/classes/
        at org.restheart.plugins.PluginsTest.mockPluginsScanner(PluginsTest.java:129)
        at org.restheart.plugins.PluginsTest.before(PluginsTest.java:56)
`

I'm having a look at this on my old PC

**Comment by dev-indb** [comment] 2024-11-18 20:13
Hello @ujibang 
Thank you for your efforts. I am facing the same issue as @mkjsix

**Comment by mkjsix** [comment] 2024-11-19 08:02
I'm now able to pass the tests but I have a runtime error on Windows only when loading plugins, I'm looking into it.

**Comment by dev-indb** [comment] 2024-11-19 09:51
Same issue here.

**Comment by mkjsix** [comment] 2024-11-19 18:38
@dev-indb please pull the latest version, I have added some fixes on how plugins are scanned on Windows.

Regarding the second issue, I can confirm I'm also not able to set the RHO environment variable on Windows as well. I'm opening a new issue about that.

**Comment by dev-indb** [comment] 2024-11-19 21:28
@mkjsix I confirm that the scanner for the plugins directory is now working properly.
Thank you very much.

**Comment by mkjsix** [comment] 2024-11-20 09:07
Thanks for your feedback @dev-indb, we are releasing RESTHeart 8.1.5 with this bug fix within few hours.

I have also closed issue https://github.com/SoftInstigate/restheart/issues/532, you might want to have a look.

**Closed by mkjsix** 2024-11-20 09:07 UTC
Labels: bug

**Comment by mkjsix** [comment] 2024-11-20 10:20
Note: to pass the RHO under Windows when it contains file system paths, you must either use double backslashes `\\`

Example:

`$Env:RHO='/logging/ansi-console->false;/core/plugins-directory->"C:\\git\\restheart\\plugins"';`

Or you must use a single slash `/`:

` $Env:RHO='/logging/ansi-console->false;/core/plugins-directory->"C:/git/restheart/plugins"';`
