### ISSUE TITLE
Restheart can't connect to existed mlab mongodb

### ISSUE THREAD

**Issue by daiping-arkte** [SoftInstigate/restheart#125] opened 2016-04-14 01:37 UTC
I am using restheart to connect my existed mlab mongodb database. But the rest api always can't work, no error found. Appreciate you if any help. Here is my working
1> Download restheart 1.1.7 from https://github.com/SoftInstigate/RESTHeart/releases
2> Modify etc/restheart.yml, only change mongo-uri values like:
mongo-uri: mongodb://username:password@ds1222333.mlab.com:17700
3> java -jar restheart.jar ./etc/restheart.yml
4> curl http://127.0.0.1:8080/db/coll (Nothing can output)
[restheart.log.txt](https://github.com/SoftInstigate/restheart/files/218228/restheart.log.txt)

**Comment by ujibang** [comment] 2016-04-14 06:18
What is the output of a GET request?

Maybe you need to specify the authdb parameter in the mongoURI...

**Comment by ujibang** [comment] 2016-04-14 06:22
Can you also try with 2.0-beta? We are going to release 2.0 in few days anyway...

**Comment by daiping-arkte** [comment] 2016-04-14 13:47
1> No difference with GET or without GET.  
2> I already included authorize info and my db name in URL.
    mongo-uri: mongodb://username:password@ds1222333.mlab.com:17700/myDB

**Comment by daiping-arkte** [comment] 2016-04-14 13:48
For new version, any change related with that? So How I can check more info restheart log?  My current log can't help.

**Comment by ujibang** [comment] 2016-04-14 20:34
Sorry we can't reproduce your issue, saying "it does not work" is just not enough to understand the issue you are experiencing. 

Try to provide as much information as you can,especially the response got from restheart. 

The authdb is not in the mongoURI, please refer to mongodb documentation to see what it is.

Also, have you tried with 2.0_beta-2 as I suggested you?

**Comment by mkjsix** [comment] 2016-04-14 20:49
I'd also set the log level to DEBUG and increase the requests-log-level to 2, just to see if we can spot anything more

```
# enable-log-console: true => log messages to the console (default value: true)
# enable-log-file: true => log messages to a file (default value: true)
# log-file-path: to specify the log file path (default value: restheart.log in system temporary directory)
# log-level: to set the log level. Value can be OFF, ERROR, WARN, INFO, DEBUG, TRACE and ALL. (default value is INFO)
# requests-log-level: log the request-response. 0 => no log, 1 => light log, 2 => detailed dump
# WARNING: use requests-log-level level 2 only for development purposes, it logs user credentials (Authorization and Auth-Token headers)
 
enable-log-file: false
#log-file-path: /tmp/restheart.log
enable-log-console: true
log-level: DEBUG
requests-log-level: 2
```

**Comment by ujibang** [comment] 2016-04-19 17:12
closing since we cannot reproduce.

@daiping-arkte feel free to reopen it specifying more information.

**Closed by ujibang** 2016-04-19 17:12 UTC
Labels: question
