### ISSUE TITLE
auth-token generation very slow on Ubuntu

### ISSUE THREAD

**Issue by Nevermind-s** [SoftInstigate/restheart#273] opened 2018-04-10 14:36 UTC
Hi, 

I deployed restheart and mongo instance with docker compose , i configured the DbBasedIdentityManager, then i created my users with hashed password, everything is going great but when it comes to authentication for the first time the request takes between 15mn and 30mn to respond with an auth token in header, the request after respond instantly until the token expires.

No info in the logs while the request is not responding.

**Comment by ujibang** [comment] 2018-04-10 15:55
Please share a reproducer

**Comment by ujibang** [comment] 2018-04-11 08:25
With reproduce I mean a way to reproduce the issue. You are using docker compose, so you should share the docker-compose.yml, restheart.yml, security.yml and a user document used to authenticate.

With that i should be able to debug the problem.

By the way, are you sure that the password stored in the users collection is bcrypted?

**Comment by Nevermind-s** [comment] 2018-04-11 10:28
Thnaks for the explanation, here is the reproducer.
Yes my passwords are bcrypted with a 0 work factor, the auth is working well but it takes too much time when the token is not in cache.


{"_id":"root","password":"$2a$10$EBT9zaSkIiUYakEcuCJnSeSIwqcQNhwbSXD4Z.aGx3FG/5nScQb9K","roles":["admins"]}

password = bcrypt("secret")

[docker-compose.txt](https://github.com/SoftInstigate/restheart/files/1898388/docker-compose.txt)
[restheart.txt](https://github.com/SoftInstigate/restheart/files/1898389/restheart.txt)
[security.txt](https://github.com/SoftInstigate/restheart/files/1898390/security.txt)

**Comment by Nevermind-s** [comment] 2018-04-16 19:55
Any solution ?

**Comment by ujibang** [comment] 2018-04-16 20:34
@Nevermind-s I tried with you configuration files.

the docker-compose.yml does not specify a volume with a configuration. I just moved restheart.yml and security.yml to a _etc_ directory and mounted it

``` yml
      ### Uncoment below if you want to mount a local configuration folder  to overwrite default restheart.yml and/or security.yml
      volumes:
         - ./etc:/opt/restheart/etc:ro
```

(note that the $PWD variable you have in your file does not work)

with these settings RESTHeart respond instantly.

``` bash
$ time http -a root:secret 127.0.0.1:8080/userbase
HTTP/1.1 200 OK
....

{
    "_embedded": [],
    "_id": "userbase",
    "_returned": 0,
    "_size": 0,
    "_total_pages": 0
}


real	0m0.445s
user	0m0.292s
sys	0m0.043s
```

**Comment by Nevermind-s** [comment] 2018-04-16 20:47
Maybe the issue comes from the vps (OVH : 1 vCore, 2Gio RAM, 10 Gio SSD) where my containers are hosted, because when i tried on my computer requests were responding instantly.

**Comment by Nevermind-s** [comment] 2018-04-21 10:53
I tested on three different IaaS (OVH, DigitalOcean and AWS), i had the same issue everytime,  requests took more than 10 minutes to respond with a 200 code and an authtoken.

**Comment by ujibang** [comment] 2018-04-21 11:36
Have you fixed the issue I spotted in your docker compose configuration file?

I have several instances of restheart running on Digital Ocean and AWS with the DbBasedIdentityManager but never had this issue and cannot repeduce it either.

Please send again your conf files and more info about the OS, docker version, etc so I can try again.

**Comment by Nevermind-s** [comment] 2018-04-21 11:55
Yeah i did.
Now i'm using a DigitalOcean droplet (1 GB 1 vCPU 25 GB), and here is the info about the os : 

``` 
Linux docker-s-1vcpu-2gb-fra1-01 4.4.0-109-generic #132-Ubuntu SMP Tue Jan 9 19:52:39 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux.
```
``` 
Docker version 17.12.0-ce, build c97c6d6
```
[restheart.txt](https://github.com/SoftInstigate/restheart/files/1934454/restheart.txt)
[docker-compose.txt](https://github.com/SoftInstigate/restheart/files/1934455/docker-compose.txt)
[security.txt](https://github.com/SoftInstigate/restheart/files/1934457/security.txt)

**Comment by ujibang** [comment] 2018-04-21 13:08
Can you also share an example request that takes that long with curl or httpie?

**Comment by Nevermind-s** [comment] 2018-04-21 13:34
All the requests are taking a long time to respond, even if the request is performed form the droplet, it is taking a while to respond,  after the first long request it goes instantly for the others when the token is still on cache.

```
http localhost:6060/_logic/roles/root -a root:secret
```

**Comment by ujibang** [comment] 2018-04-21 14:46
Isn't port 8080?

**Comment by Nevermind-s** [comment] 2018-04-21 14:58
I changed the port for test purpose.

**Comment by ujibang** [comment] 2018-04-21 16:35
I can't reproduce it. I just tried in a EC2 AWS instance (t2.micro, with 1Gb of RAM), installed docker-compose and use your files to start restheart and mongodb containers, and **it works as expected**.

I put restheart.yml and security.yml in a etc directory:

```
$ ls
docker-compose.yml  etc
$ ls etc
restheart.yml  security.yml
```

I created the root use in the userbase._accounts as follows:

```
$ sudo docker exec -it mongodb /bin/bash    <= this opens a shell in the mongodb container
$ mongo -u admin -p --authenticationDatabase "admin"
> use userbase
> db.getCollection("_accounts")..insert({"_id":"root","password":"$2a$10$EBT9zaSkIiUYakEcuCJnSeSIwqcQNhwbSXD4Z.aGx3FG/5nScQb9K","roles":["admins"]})
> exit  <=  exit from mongo shell
$ exit  <= exit from mongodb container
```

then I tried restheart and it work as expected:

```
$ time curl -u root:secret -v 127.0.0.1:8080
..... 
{"_embedded":[{"_id":"config"},{"_id":"test"},{"_id":"userbase"}],"_size":3,"_total_pages":1,"_returned":3}
real	0m0.142s
user	0m0.004s
sys	0m0.000s
```

The only thing that I've changed in your files is that I commented out `build .` from docker-compose.yml

```
services:
   restheart:
      # build: .
```

**Comment by Nevermind-s** [comment] 2018-04-23 11:15
Sorry to bother you, but i've been trying all day, and the issue persists.
Can i send you by email my .pem key so you might take a look on my EC2 Instance ?

**Comment by ujibang** [comment] 2018-04-23 11:44
Yes please, andrea (at) softinstigate.com

**Comment by ujibang** [comment] 2018-04-23 22:19
I gave your installation a look and I can see the problem on your ec2 instance. 

What I found so far is:

- the DbIdentityManager is properly configured. Passing a wrong username or password returns `401 Unauthorized` instantly (this involves a query so restheart can actually communicate with mongodb)
- an OPTIONS request also works without any delay
- curl hangs when passing valid credentials!

I tried updating docker but nothing changed.

In my test I used Amazon Linux AMI. In your case it is Ubuntu 16.04.4 LTS (can you confirm?). Have you used Ubuntu 16 also in the other cases that you mentioned (Digital Ocean, OVH, etc)?

Please try with Amazon Linux AMI (this comes with docker preinstalled, you just need to install docker-compose (see http://magescale.com/installing-docker-docker-compose-on-aws-linux-ami/) and let me know.

**Comment by ujibang** [comment] 2018-04-24 05:44
I found the issue. The problem is with the `auth-token-enabled` option.

Disabling it fixes the issue. Also using restheart version 3.2.2 works.

We recently changed the way the auth token is generated, see commit https://github.com/SoftInstigate/restheart/commit/746e836190ade62d70b81e6b740b806ccee0e778

I'm very surprise that it takes so long when restheart rungs with docker on Ubuntu, I'll dig into it.

**Comment by ujibang** [comment] 2018-04-24 07:35
for reference https://stackoverflow.com/questions/137212/how-to-solve-slow-java-securerandom

**Comment by ujibang** [comment] 2018-04-24 07:53
fixed in latest build.
I also updated your docker images and tested it.

**Closed by ujibang** 2018-04-24 07:53 UTC

**Comment by Nevermind-s** [comment] 2018-04-24 08:40
Thanks you are amazing 😀 !
